# Generated by Django 6.1 on 2026-09-06 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('current_agent', models.CharField(default='data_analyzer', max_length=100)),
                ('current_supervisor', models.CharField(default='financial_supervisor', max_length=100)),
                ('selected_llm', models.CharField(blank=True, max_length=100, null=True)),
                ('fallback_used', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutingDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supervisor', models.CharField(max_length=100)),
                ('selected_target', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_decisions', to='workflows_api.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_text', models.TextField()),
                ('llm_model', models.CharField(max_length=100)),
                ('generation_attempt', models.IntegerField(default=1)),
                ('validation_status', models.CharField(default='PENDING', max_length=20)),
                ('validation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='workflows_api.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('source', models.CharField(default='DataAnalyzer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='workflows_api.workflow')),
            ],
        ),
    ]
