# Generated by Django 6.1 on 2026-09-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='simplified_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
