# Generated by Django 6.1 on 2026-09-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows_api', '0002_workflow_simplified_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='document_sections',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='current_agent',
            field=models.CharField(default='document_decomposer', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='current_supervisor',
            field=models.CharField(default='master_orchestrator', max_length=100),
        ),
    ]
