# Generated by Django 6.1 on 2026-09-07 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('section', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file_name', models.CharField(max_length=255)),
                ('normalized_file_type', models.CharField(max_length=50)),
                ('stored_file_path', models.CharField(max_length=512)),
                ('chroma_collection_name', models.CharField(default='user_knowledge_base', max_length=255)),
                ('total_chunks', models.IntegerField(default=0)),
                ('ingestion_status', models.CharField(choices=[('PENDING', 'Pending'), ('INDEXED', 'Indexed'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingested_documents', to='api.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentExecutionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('final_output', models.TextField(blank=True, default='')),
                ('retry_iterations', models.IntegerField(default=0)),
                ('evaluation_passed', models.BooleanField(default=False)),
                ('hallucination_report', models.JSONField(blank=True, default=dict)),
                ('execution_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('execution_duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='api.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
